/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CardList.java
 *
 * Created on Sep 15, 2013, 6:44:48 PM
 */
package bprm;



import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kaveh
 */
public class CardList extends javax.swing.JFrame {

    /** Creates new form CardList */
    public CardList() {
        initComponents();
        df.addColumn("");
        bc=new ButtonColumn(jTable1, null, 5);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTable1.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BRP Maker");

        jButton1.setFont(new java.awt.Font("Iranian Sans", 1, 12));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bprm/add.png"))); // NOI18N
        jButton1.setText("افزودن کارت");
        jButton1.setToolTipText("ایجاد کارت جدید");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Iranian Sans", 1, 12));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bprm/document-import.png"))); // NOI18N
        jButton2.setText("ایجاد فلش کارت");
        jButton2.setToolTipText("ساخت فلش کارت BRP");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setModel(df);
        jTable1.setCellSelectionEnabled(true);
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setBackground(Utils.main_color);
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bprm/brain.png"))); // NOI18N
        jLabel1.setText(Utils.flashcard_name);
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    count++;
    ViewCard addc=new ViewCard();
    addc.setVisible(true);
    //addc.setModalityType(ModalityType.MODELESS);
    Object[] ob={"","","","",count,"حذف"};
    df.addRow(ob);
    if(count>=1)
        jButton2.setEnabled(false);
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new CardList().setVisible(true);

            }
        });
    }
    public static int count = 0;
    private DefaultTableModel df=new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "تصویر پاسخ", "تصویر سوال", "پاسخ", "سوال", ""
            }
        ) {
             Class[] types = new Class [] {
               java.lang.String.class, java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.Integer.class , java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false , true
            };

        @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
    private ButtonColumn bc;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void manageForm() {
        if (count == 0) {
            jButton2.setEnabled(false);
        }
        else
            jButton2.setEnabled(true);
//     buttonDelete.addTableButtonListener(new TableButtonListener() {
//         @Override
//            public void tableButtonClicked(int row, int col) {
//                 JOptionPane.showMessageDialog(null, row+" "+col);
//             }     
//            });        
//        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
//addWindowListener(new WindowAdapter() {
//@Override
//public void windowClosing(WindowEvent we)
//{ 
// String ObjButtons[] = {"بله","خیر"};
// int PromptResult = JOptionPane.showOptionDialog(null,"برای بازگشت اطمینان دارید؟","BRP Maker",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,ObjButtons,ObjButtons[1]);
//  if(PromptResult==JOptionPane.YES_OPTION)
//  {
//    System.exit(0);
//  }
//}
//});
    }
}
